apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: app
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: wordpress
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: app
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
      annotations:
        backup.velero.io/backup-volumes: "app-storage"
    spec:
      containers:
      - name: app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: wp_host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: wp_database
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: wp_user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
             secretKeyRef:
               name: database-password
               key: database_password
        ports:
        - containerPort: 80
          name: app-port
        volumeMounts:
        - name: app-storage
          mountPath: /var/www/html/wp-content/uploads/
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc
