apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-app
  namespace: app
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-app-backup
            image: expert360/kubectl-awscli:v1.11.2
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: aws_secret_access_key
            command: [ "/bin/bash", "-c", "aws s3 sync s3://karimlabs-app-backup/ /data/backup" ]
            volumeMounts:
              - name: backup-aws
                mountPath: /data/backup
          volumes:
            - name: backup-aws
              persistentVolumeClaim:
                claimName: app-pvc
          restartPolicy: Never
