apiVersion: v1
kind: Secret
metadata:
  name: database-password
  namespace: app
type: Opaque
data:
  database_password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: rootdb-password
  namespace: app
type: Opaque
data:
  rootdb_password: cGFzc3dvcmQ=
